### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by antosha417** [mishakrengauz/prog_Krengauz#1]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by mishakrengauz** [comment]
Понял, сейчас буду исправлять, спасибо!

**Comment by mishakrengauz** [comment]
Я поправил программу, теперь все по пеп8. 040d3850a3270c0670e2228dc0420982b1c2422f
