### ISSUE TITLE
Нужно закрывать окно 

### ISSUE THREAD

**Issue by antosha417** [mishakrengauz/prog_Krengauz#2]
https://github.com/mishakrengauz/prog_Krengauz/blob/84091c084bdaabfbaca30d1d9aa65b8ec9a319a4/house.py#L112
Не забывай в конце писать 
```
window.getMouse()   
window.close()
```

**Comment by mishakrengauz** [comment]
@antosha417 , Добрый вечер! Я исправил. 48ffde4f00442d45039e7da7c8d4eb77965e5236

**Comment by mishakrengauz** [comment]
@antosha417 Исправил pep8: 3d768c875320670f64e9b1b032ebcd5d4a2c6c92
